openapi: 3.2.0
info:
  title: Eclipse RESTful User Profiles API
  description: This describes the resources that make up the official Eclipse Foundation REST API.
  contact: {}
  version: '1.0'
servers:
- url: https://api.eclipse.org
  description: The production API server
tags:
- name: User Profiles
  description: 'User information is available trought this resource. Some private information,

    is included when authenticated through OAuth with the `profile` scope.'
paths:
  /account/profile:
    get:
      tags:
      - User Profiles
      summary: Current user
      description: Retrieve profile information about current user.
      operationId: CurrentUser
      parameters: []
      responses:
        '200':
          description: ''
          headers:
            X-Rate-Limit-Limit:
              $ref: '#/components/headers/X-RateLimit-Limit'
            X-Rate-Limit-Remaining:
              $ref: '#/components/headers/X-RateLimit-Remaining'
            X-Rate-Limit-Reset:
              $ref: '#/components/headers/X-RateLimit-Reset'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Currentuserresponse'
                description: ''
              example:
              - uid: 9
                name: cguindon
                mail: chris.guindon@eclipse-foundation.org
                eca:
                  signed: true
                is_committer: true
                friends:
                  friend_id: 6104
                first_name: Christopher
                last_name: Guindon
                twitter_handle: chrisguindon
                org: Eclipse Foundation
                job_title: Lead Web Application Developper
                website: http://www.chrisguindon.com/
                country:
                  code: CA
                  name: Canada
                bio: Hello world! When I am not at a computer, which is rare, I spend my time playing the drums, watching hockey or at the top of a hill snowboarding. I am also very passionate about music and live concerts!
                interests:
                - Snowboarding
                - webdev
                - php
                - javascript
                - Drums
      deprecated: false
  /account/profile/{name}:
    get:
      tags:
      - User Profiles
      summary: Retrieve user
      description: Retrieve profile information about a specified user.
      operationId: RetrieveUser
      parameters:
      - name: name
        in: path
        description: A valid Eclipse username.
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        '200':
          description: ''
          headers:
            X-Rate-Limit-Limit:
              $ref: '#/components/headers/X-RateLimit-Limit'
            X-Rate-Limit-Remaining:
              $ref: '#/components/headers/X-RateLimit-Remaining'
            X-Rate-Limit-Reset:
              $ref: '#/components/headers/X-RateLimit-Reset'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Retrieveuserresponse'
              example:
                uid: 9
                name: cguindon
                mail: chris.guindon@eclipse-foundation.org
                eca:
                  signed: true
                is_committer: true
                friends:
                  friend_id: 6104
                first_name: Christopher
                last_name: Guindon
                twitter_handle: chrisguindon
                org: Eclipse Foundation
                job_title: Lead Web Application Developper
                website: http://www.chrisguindon.com/
                country:
                  code: CA
                  name: Canada
                bio: Hello world! When I am not at a computer, which is rare, I spend my time playing the drums, watching hockey or at the top of a hill snowboarding. I am also very passionate about music and live concerts!
                interests:
                - Snowboarding
                - webdev
                - php
                - javascript
                - Drums
      deprecated: false
  /account/profile/:
    get:
      tags:
      - User Profiles
      summary: Search for a user
      description: Search for a user by uid, name or mail. The uid will be used first, then the name and if no user was found, the server will try to load a user by mail.
      operationId: SearchForAUser
      parameters:
      - name: uid
        in: query
        description: A valid User ID.
        style: form
        explode: true
        schema:
          type: integer
          format: int32
      - name: name
        in: query
        description: A valid username.
        style: form
        explode: true
        schema:
          type: string
      - name: mail
        in: query
        description: A valid encoded mail.
        style: form
        explode: true
        schema:
          type: string
      responses:
        '200':
          description: ''
          headers:
            X-Rate-Limit-Limit:
              $ref: '#/components/headers/X-RateLimit-Limit'
            X-Rate-Limit-Remaining:
              $ref: '#/components/headers/X-RateLimit-Remaining'
            X-Rate-Limit-Reset:
              $ref: '#/components/headers/X-RateLimit-Reset'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Searchforauserresponse'
                description: ''
              example:
              - uid: 9
                name: cguindon
                mail: chris.guindon@eclipse-foundation.org
                eca:
                  signed: true
                is_committer: true
                friends:
                  friend_id: 6104
                first_name: Christopher
                last_name: Guindon
                twitter_handle: chrisguindon
                org: Eclipse Foundation
                job_title: Lead Web Application Developper
                website: http://www.chrisguindon.com/
                country:
                  code: CA
                  name: Canada
                bio: Hello world! When I am not at a computer, which is rare, I spend my time playing the drums, watching hockey or at the top of a hill snowboarding. I am also very passionate about music and live concerts!
                interests:
                - Snowboarding
                - webdev
                - php
                - javascript
                - Drums
      deprecated: false
  /account/profile/{name}/forum:
    get:
      tags:
      - User Profiles
      summary: Forum posts
      description: This method returns forum post associated with a user.
      operationId: ForumPosts
      parameters:
      - name: name
        in: path
        description: A valid Eclipse username.
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        '200':
          description: ''
          headers:
            Link:
              content:
                text/plain:
                  schema:
                    type: string
                  example: <https://api.eclipse.org/account/profile/cguindon/forum?page=1&amp;pagesize=20>; rel="last", <https://api.eclipse.org/account/profile/cguindon/forum?page=1&amp;pagesize=20>; rel="first", <https://api.eclipse.org/account/profile/cguindon/forum?page=1&amp;pagesize=20>; rel="self"
            X-Rate-Limit-Limit:
              $ref: '#/components/headers/X-RateLimit-Limit'
            X-Rate-Limit-Remaining:
              $ref: '#/components/headers/X-RateLimit-Remaining'
            X-Rate-Limit-Reset:
              $ref: '#/components/headers/X-RateLimit-Reset'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Forumpostsresponse'
              example:
                id: 125133
                alias: Christopher Guindon
                avatar_loc: null
                email: chris.guindon@eclipse-foundation.org
                posted_msg_count: 2
                join_date: 1329944087
                location: null
                sig: null
                last_visit: 1489180635
                level_name: Junior Member
                level_img: null
                posts:
                - msg_id: 1385038
                  msg_thread_id: 781490
                  msg_poster_id: 125133
                  msg_reply_to: 0
                  msg_post_stamp: 1401828571
                  msg_update_stamp: 0
                  msg_updated_by: 0
                  msg_subject: sdfdsf
                  thread_id: 781490
                  thread_forum_id: 97
                  thread_root_msg_id: 1385038
                  thread_last_post_date: 1490969896
                  thread_replies: 6
                  thread_views: 8925
                  thread_rating: 0
                  thread_n_rating: 0
                  thread_last_post_id: 1758673
                  thread_orderexpiry: 0
                  thread_thread_opt: 0
                  thread_tdescr: ''
                  forum_name: Test
                  forum_cat_id: 3
                  forum_description: Forum for testing messages. This is <b>UNRELATED to testing with Eclipse</b>.  Use the <a href='http://www.eclipse.org/forums/eclipse.tptp'>Test and Performance forum</a> for those discussions instead.
                  forum_date_created: 1248707241
                  forum_thread_count: 975
                  forum_post_count: 1526
                  forum_last_post_id: 1764500
                  cat_name: General (non-technical)
                  cat_description: ' - Click +/- to expand/collapse'
                  read_last_view: null
                  last_msg_poster_id: 216471
                  last_msg_subject: 'Re: sdfdsf'
                  last_msg_post_stamp: 1490969896
                  last_msg_update_stamp: 0
                  last_poster_email: m.amjadi@engineer.com
                  last_poster_alias: Mohammad H. Amir Amjadi
                  root_msg_poster_id: 125133
                  root_msg_subject: sdfdsf
                  root_msg_post_stamp: 1401828571
                  root_msg_update_stamp: 0
                  root_poster_email: chris.guindon@eclipse-foundation.org
                  root_poster_alias: Christopher Guindon
                  last_user_msg_poster_id: 125133
                  last_user_msg_subject: sdfdsf
                  last_user_msg_stamp: 1401828571
                  msg4_update_stamp: 0
                  msg_group_post_stamp: 1479327581
      deprecated: false
  /account/profile/{name}/projects:
    get:
      tags:
      - User Profiles
      summary: Project Relationship
      description: This call returns a list of project affiliations for a particular user.
      operationId: ProjectRelationship
      parameters:
      - name: name
        in: path
        description: A valid Eclipse username.
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        '200':
          description: ''
          headers:
            X-Rate-Limit-Limit:
              $ref: '#/components/headers/X-RateLimit-Limit'
            X-Rate-Limit-Remaining:
              $ref: '#/components/headers/X-RateLimit-Remaining'
            X-Rate-Limit-Reset:
              $ref: '#/components/headers/X-RateLimit-Reset'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectRelationshipresponse'
              example:
                technology.cbi:
                - ActiveDate: '2014-12-15'
                  InactiveDate: null
                  EditBugs: 0
                  ProjectName: Common Build Infrastructure
                  url: https://projects.eclipse.org/projects/technology.cbi
                  Relation:
                    Relation: CM
                    Description: Committer
                    IsActive: 1
                    Type:
                      Type: PR
                      Description: Person - Project
                technology.usssdk:
                - ActiveDate: '2016-09-21'
                  InactiveDate: null
                  EditBugs: 0
                  ProjectName: Eclipse USS SDK
                  url: https://projects.eclipse.org/projects/technology.usssdk
                  Relation:
                    Relation: CM
                    Description: Committer
                    IsActive: 1
                    Type:
                      Type: PR
                      Description: Person - Project
                - ActiveDate: '2016-09-21'
                  InactiveDate: null
                  EditBugs: 0
                  ProjectName: Eclipse USS SDK
                  url: https://projects.eclipse.org/projects/technology.usssdk
                  Relation:
                    Relation: PL
                    Description: Project Lead
                    IsActive: 1
                    Type:
                      Type: PR
                      Description: Person - Project
                foundation-internal:
                - ActiveDate: '2012-12-21'
                  InactiveDate: null
                  EditBugs: 0
                  ProjectName: Internal Foundation Projects
                  url: ''
                  Relation:
                    Relation: CM
                    Description: Committer
                    IsActive: 1
                    Type:
                      Type: PR
                      Description: Person - Project
      deprecated: false
  /account/profile/{name}/gerrit:
    get:
      tags:
      - User Profiles
      summary: Gerrit review count
      description: This method returns gerrit review count for a user.
      operationId: GerritReviewCount
      parameters:
      - name: name
        in: path
        description: A valid Eclipse username.
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        '200':
          description: ''
          headers:
            X-Rate-Limit-Limit:
              $ref: '#/components/headers/X-RateLimit-Limit'
            X-Rate-Limit-Remaining:
              $ref: '#/components/headers/X-RateLimit-Remaining'
            X-Rate-Limit-Reset:
              $ref: '#/components/headers/X-RateLimit-Reset'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Gerritreviewcountresponse'
              example:
                merged_changes_count: 671
      deprecated: false
  /account/profile/{name}/mailing-list:
    get:
      tags:
      - User Profiles
      summary: Mailing List Subscriptions
      description: This method returns mailing list subscriptions for a user.
      operationId: MailingListSubscriptions
      parameters:
      - name: name
        in: path
        description: A valid Eclipse username.
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        '200':
          description: ''
          headers:
            X-Rate-Limit-Limit:
              $ref: '#/components/headers/X-RateLimit-Limit'
            X-Rate-Limit-Remaining:
              $ref: '#/components/headers/X-RateLimit-Remaining'
            X-Rate-Limit-Reset:
              $ref: '#/components/headers/X-RateLimit-Reset'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MailingListSubscriptionsresponse'
              example:
                mailing_list_subscriptions:
                - list_name: epp-dev
                  list_description: Eclipse Packaging Project
                - list_name: eclipse.org-webdev
                  list_description: Eclipse.org Webdev notices and discussions
      deprecated: false
components:
  schemas:
    Relation:
      title: Relation
      required:
      - Relation
      - Description
      - IsActive
      - Type
      type: object
      properties:
        Relation:
          type: string
        Description:
          type: string
        IsActive:
          type: string
        Type:
          $ref: '#/components/schemas/Type'
      example:
        Relation: CM
        Description: Committer
        IsActive: 1
        Type:
          Type: PR
          Description: Person - Project
    Searchforauserresponse:
      title: Searchforauserresponse
      required:
      - uid
      - name
      - mail
      - eca
      - is_committer
      - friends
      - first_name
      - last_name
      - twitter_handle
      - org
      - job_title
      - website
      - country
      - bio
      - interests
      type: object
      properties:
        uid:
          type: string
        name:
          type: string
        mail:
          type: string
        eca:
          $ref: '#/components/schemas/Eca'
        is_committer:
          type: boolean
        friends:
          $ref: '#/components/schemas/Friends'
        first_name:
          type: string
        last_name:
          type: string
        twitter_handle:
          type: string
        org:
          type: string
        job_title:
          type: string
        website:
          type: string
        country:
          $ref: '#/components/schemas/Country'
        bio:
          type: string
        interests:
          type: array
          items:
            type: string
          description: ''
      example:
        uid: 9
        name: cguindon
        mail: chris.guindon@eclipse-foundation.org
        eca:
          signed: true
        is_committer: true
        friends:
          friend_id: 6104
        first_name: Christopher
        last_name: Guindon
        twitter_handle: chrisguindon
        org: Eclipse Foundation
        job_title: Lead Web Application Developper
        website: http://www.chrisguindon.com/
        country:
          code: CA
          name: Canada
        bio: Hello world! When I am not at a computer, which is rare, I spend my time playing the drums, watching hockey or at the top of a hill snowboarding. I am also very passionate about music and live concerts!
        interests:
        - Snowboarding
        - webdev
        - php
        - javascript
        - Drums
    Retrieveuserresponse:
      title: Retrieveuserresponse
      required:
      - uid
      - name
      - mail
      - eca
      - is_committer
      - friends
      - first_name
      - last_name
      - twitter_handle
      - org
      - job_title
      - website
      - country
      - bio
      - interests
      type: object
      properties:
        uid:
          type: string
        name:
          type: string
        mail:
          type: string
        eca:
          $ref: '#/components/schemas/Eca'
        is_committer:
          type: boolean
        friends:
          $ref: '#/components/schemas/Friends'
        first_name:
          type: string
        last_name:
          type: string
        twitter_handle:
          type: string
        org:
          type: string
        job_title:
          type: string
        website:
          type: string
        country:
          $ref: '#/components/schemas/Country'
        bio:
          type: string
        interests:
          type: array
          items:
            type: string
          description: ''
      example:
        uid: 9
        name: cguindon
        mail: chris.guindon@eclipse-foundation.org
        eca:
          signed: true
        is_committer: true
        friends:
          friend_id: 6104
        first_name: Christopher
        last_name: Guindon
        twitter_handle: chrisguindon
        org: Eclipse Foundation
        job_title: Lead Web Application Developper
        website: http://www.chrisguindon.com/
        country:
          code: CA
          name: Canada
        bio: Hello world! When I am not at a computer, which is rare, I spend my time playing the drums, watching hockey or at the top of a hill snowboarding. I am also very passionate about music and live concerts!
        interests:
        - Snowboarding
        - webdev
        - php
        - javascript
        - Drums
    Gerritreviewcountresponse:
      title: Gerritreviewcountresponse
      required:
      - merged_changes_count
      type: object
      properties:
        merged_changes_count:
          type: string
      example:
        merged_changes_count: 671
    Forumpostsresponse:
      title: Forumpostsresponse
      required:
      - id
      - alias
      - avatar_loc
      - email
      - posted_msg_count
      - join_date
      - location
      - sig
      - last_visit
      - level_name
      - level_img
      - posts
      type: object
      properties:
        id:
          type: string
        alias:
          type: string
        avatar_loc:
          type:
          - string
          - 'null'
        email:
          type: string
        posted_msg_count:
          type: string
        join_date:
          type: string
        location:
          type:
          - string
          - 'null'
        sig:
          type:
          - string
          - 'null'
        last_visit:
          type: string
        level_name:
          type: string
        level_img:
          type:
          - string
          - 'null'
        posts:
          type: array
          items:
            $ref: '#/components/schemas/Post'
          description: ''
      example:
        id: 125133
        alias: Christopher Guindon
        avatar_loc: null
        email: chris.guindon@eclipse-foundation.org
        posted_msg_count: 2
        join_date: 1329944087
        location: null
        sig: null
        last_visit: 1489180635
        level_name: Junior Member
        level_img: null
        posts:
        - msg_id: 1385038
          msg_thread_id: 781490
          msg_poster_id: 125133
          msg_reply_to: 0
          msg_post_stamp: 1401828571
          msg_update_stamp: 0
          msg_updated_by: 0
          msg_subject: sdfdsf
          thread_id: 781490
          thread_forum_id: 97
          thread_root_msg_id: 1385038
          thread_last_post_date: 1490969896
          thread_replies: 6
          thread_views: 8925
          thread_rating: 0
          thread_n_rating: 0
          thread_last_post_id: 1758673
          thread_orderexpiry: 0
          thread_thread_opt: 0
          thread_tdescr: ''
          forum_name: Test
          forum_cat_id: 3
          forum_description: Forum for testing messages. This is <b>UNRELATED to testing with Eclipse</b>.  Use the <a href='http://www.eclipse.org/forums/eclipse.tptp'>Test and Performance forum</a> for those discussions instead.
          forum_date_created: 1248707241
          forum_thread_count: 975
          forum_post_count: 1526
          forum_last_post_id: 1764500
          cat_name: General (non-technical)
          cat_description: ' - Click +/- to expand/collapse'
          read_last_view: null
          last_msg_poster_id: 216471
          last_msg_subject: 'Re: sdfdsf'
          last_msg_post_stamp: 1490969896
          last_msg_update_stamp: 0
          last_poster_email: m.amjadi@engineer.com
          last_poster_alias: Mohammad H. Amir Amjadi
          root_msg_poster_id: 125133
          root_msg_subject: sdfdsf
          root_msg_post_stamp: 1401828571
          root_msg_update_stamp: 0
          root_poster_email: chris.guindon@eclipse-foundation.org
          root_poster_alias: Christopher Guindon
          last_user_msg_poster_id: 125133
          last_user_msg_subject: sdfdsf
          last_user_msg_stamp: 1401828571
          msg4_update_stamp: 0
          msg_group_post_stamp: 1479327581
    FoundationInternal:
      title: FoundationInternal
      required:
      - ActiveDate
      - InactiveDate
      - EditBugs
      - ProjectName
      - url
      - Relation
      type: object
      properties:
        ActiveDate:
          type: string
        InactiveDate:
          type:
          - string
          - 'null'
        EditBugs:
          type: string
        ProjectName:
          type: string
        url:
          type: string
        Relation:
          $ref: '#/components/schemas/Relation'
      example:
        ActiveDate: '2012-12-21'
        InactiveDate: null
        EditBugs: 0
        ProjectName: Internal Foundation Projects
        url: ''
        Relation:
          Relation: CM
          Description: Committer
          IsActive: 1
          Type:
            Type: PR
            Description: Person - Project
    ProjectRelationshipresponse:
      title: ProjectRelationshipresponse
      required:
      - technology.cbi
      - technology.usssdk
      - foundation-internal
      type: object
      properties:
        technology.cbi:
          type: array
          items:
            $ref: '#/components/schemas/TechnologyCbi'
          description: ''
        technology.usssdk:
          type: array
          items:
            $ref: '#/components/schemas/TechnologyUsssdk'
          description: ''
        foundation-internal:
          type: array
          items:
            $ref: '#/components/schemas/FoundationInternal'
          description: ''
      example:
        technology.cbi:
        - ActiveDate: '2014-12-15'
          InactiveDate: null
          EditBugs: 0
          ProjectName: Common Build Infrastructure
          url: https://projects.eclipse.org/projects/technology.cbi
          Relation:
            Relation: CM
            Description: Committer
            IsActive: 1
            Type:
              Type: PR
              Description: Person - Project
        technology.usssdk:
        - ActiveDate: '2016-09-21'
          InactiveDate: null
          EditBugs: 0
          ProjectName: Eclipse USS SDK
          url: https://projects.eclipse.org/projects/technology.usssdk
          Relation:
            Relation: CM
            Description: Committer
            IsActive: 1
            Type:
              Type: PR
              Description: Person - Project
        - ActiveDate: '2016-09-21'
          InactiveDate: null
          EditBugs: 0
          ProjectName: Eclipse USS SDK
          url: https://projects.eclipse.org/projects/technology.usssdk
          Relation:
            Relation: PL
            Description: Project Lead
            IsActive: 1
            Type:
              Type: PR
              Description: Person - Project
        foundation-internal:
        - ActiveDate: '2012-12-21'
          InactiveDate: null
          EditBugs: 0
          ProjectName: Internal Foundation Projects
          url: ''
          Relation:
            Relation: CM
            Description: Committer
            IsActive: 1
            Type:
              Type: PR
              Description: Person - Project
    Post:
      title: Post
      required:
      - msg_id
      - msg_thread_id
      - msg_poster_id
      - msg_reply_to
      - msg_post_stamp
      - msg_update_stamp
      - msg_updated_by
      - msg_subject
      - thread_id
      - thread_forum_id
      - thread_root_msg_id
      - thread_last_post_date
      - thread_replies
      - thread_views
      - thread_rating
      - thread_n_rating
      - thread_last_post_id
      - thread_orderexpiry
      - thread_thread_opt
      - thread_tdescr
      - forum_name
      - forum_cat_id
      - forum_description
      - forum_date_created
      - forum_thread_count
      - forum_post_count
      - forum_last_post_id
      - cat_name
      - cat_description
      - read_last_view
      - last_msg_poster_id
      - last_msg_subject
      - last_msg_post_stamp
      - last_msg_update_stamp
      - last_poster_email
      - last_poster_alias
      - root_msg_poster_id
      - root_msg_subject
      - root_msg_post_stamp
      - root_msg_update_stamp
      - root_poster_email
      - root_poster_alias
      - last_user_msg_poster_id
      - last_user_msg_subject
      - last_user_msg_stamp
      - msg4_update_stamp
      - msg_group_post_stamp
      type: object
      properties:
        msg_id:
          type: string
        msg_thread_id:
          type: string
        msg_poster_id:
          type: string
        msg_reply_to:
          type: string
        msg_post_stamp:
          type: string
        msg_update_stamp:
          type: string
        msg_updated_by:
          type: string
        msg_subject:
          type: string
        thread_id:
          type: string
        thread_forum_id:
          type: string
        thread_root_msg_id:
          type: string
        thread_last_post_date:
          type: string
        thread_replies:
          type: string
        thread_views:
          type: string
        thread_rating:
          type: string
        thread_n_rating:
          type: string
        thread_last_post_id:
          type: string
        thread_orderexpiry:
          type: string
        thread_thread_opt:
          type: string
        thread_tdescr:
          type: string
        forum_name:
          type: string
        forum_cat_id:
          type: string
        forum_description:
          type: string
        forum_date_created:
          type: string
        forum_thread_count:
          type: string
        forum_post_count:
          type: string
        forum_last_post_id:
          type: string
        cat_name:
          type: string
        cat_description:
          type: string
        read_last_view:
          type:
          - string
          - 'null'
        last_msg_poster_id:
          type: string
        last_msg_subject:
          type: string
        last_msg_post_stamp:
          type: string
        last_msg_update_stamp:
          type: string
        last_poster_email:
          type: string
        last_poster_alias:
          type: string
        root_msg_poster_id:
          type: string
        root_msg_subject:
          type: string
        root_msg_post_stamp:
          type: string
        root_msg_update_stamp:
          type: string
        root_poster_email:
          type: string
        root_poster_alias:
          type: string
        last_user_msg_poster_id:
          type: string
        last_user_msg_subject:
          type: string
        last_user_msg_stamp:
          type: string
        msg4_update_stamp:
          type: string
        msg_group_post_stamp:
          type: string
      example:
        msg_id: 1385038
        msg_thread_id: 781490
        msg_poster_id: 125133
        msg_reply_to: 0
        msg_post_stamp: 1401828571
        msg_update_stamp: 0
        msg_updated_by: 0
        msg_subject: sdfdsf
        thread_id: 781490
        thread_forum_id: 97
        thread_root_msg_id: 1385038
        thread_last_post_date: 1490969896
        thread_replies: 6
        thread_views: 8925
        thread_rating: 0
        thread_n_rating: 0
        thread_last_post_id: 1758673
        thread_orderexpiry: 0
        thread_thread_opt: 0
        thread_tdescr: ''
        forum_name: Test
        forum_cat_id: 3
        forum_description: Forum for testing messages. This is <b>UNRELATED to testing with Eclipse</b>.  Use the <a href='http://www.eclipse.org/forums/eclipse.tptp'>Test and Performance forum</a> for those discussions instead.
        forum_date_created: 1248707241
        forum_thread_count: 975
        forum_post_count: 1526
        forum_last_post_id: 1764500
        cat_name: General (non-technical)
        cat_description: ' - Click +/- to expand/collapse'
        read_last_view: null
        last_msg_poster_id: 216471
        last_msg_subject: 'Re: sdfdsf'
        last_msg_post_stamp: 1490969896
        last_msg_update_stamp: 0
        last_poster_email: m.amjadi@engineer.com
        last_poster_alias: Mohammad H. Amir Amjadi
        root_msg_poster_id: 125133
        root_msg_subject: sdfdsf
        root_msg_post_stamp: 1401828571
        root_msg_update_stamp: 0
        root_poster_email: chris.guindon@eclipse-foundation.org
        root_poster_alias: Christopher Guindon
        last_user_msg_poster_id: 125133
        last_user_msg_subject: sdfdsf
        last_user_msg_stamp: 1401828571
        msg4_update_stamp: 0
        msg_group_post_stamp: 1479327581
    Type:
      title: Type
      required:
      - Type
      - Description
      type: object
      properties:
        Type:
          type: string
        Description:
          type: string
      example:
        Type: PR
        Description: Person - Project
    MailingListSubscriptionsresponse:
      title: MailingListSubscriptionsresponse
      required:
      - mailing_list_subscriptions
      type: object
      properties:
        mailing_list_subscriptions:
          type: array
          items:
            $ref: '#/components/schemas/MailingListSubscription'
          description: ''
      example:
        mailing_list_subscriptions:
        - list_name: epp-dev
          list_description: Eclipse Packaging Project
        - list_name: eclipse.org-webdev
          list_description: Eclipse.org Webdev notices and discussions
    MailingListSubscription:
      title: MailingListSubscription
      required:
      - list_name
      - list_description
      type: object
      properties:
        list_name:
          type: string
        list_description:
          type: string
      example:
        list_name: epp-dev
        list_description: Eclipse Packaging Project
    Friends:
      title: Friends
      required:
      - friend_id
      type: object
      properties:
        friend_id:
          type: string
      example:
        friend_id: 6104
    TechnologyUsssdk:
      title: TechnologyUsssdk
      required:
      - ActiveDate
      - InactiveDate
      - EditBugs
      - ProjectName
      - url
      - Relation
      type: object
      properties:
        ActiveDate:
          type: string
        InactiveDate:
          type:
          - string
          - 'null'
        EditBugs:
          type: string
        ProjectName:
          type: string
        url:
          type: string
        Relation:
          $ref: '#/components/schemas/Relation'
      example:
        ActiveDate: '2016-09-21'
        InactiveDate: null
        EditBugs: 0
        ProjectName: Eclipse USS SDK
        url: https://projects.eclipse.org/projects/technology.usssdk
        Relation:
          Relation: CM
          Description: Committer
          IsActive: 1
          Type:
            Type: PR
            Description: Person - Project
    TechnologyCbi:
      title: TechnologyCbi
      required:
      - ActiveDate
      - InactiveDate
      - EditBugs
      - ProjectName
      - url
      - Relation
      type: object
      properties:
        ActiveDate:
          type: string
        InactiveDate:
          type:
          - string
          - 'null'
        EditBugs:
          type: string
        ProjectName:
          type: string
        url:
          type: string
        Relation:
          $ref: '#/components/schemas/Relation'
      example:
        ActiveDate: '2014-12-15'
        InactiveDate: null
        EditBugs: 0
        ProjectName: Common Build Infrastructure
        url: https://projects.eclipse.org/projects/technology.cbi
        Relation:
          Relation: CM
          Description: Committer
          IsActive: 1
          Type:
            Type: PR
            Description: Person - Project
    Eca:
      title: Eca
      required:
      - signed
      type: object
      properties:
        signed:
          type: boolean
      example:
        signed: true
    Country:
      title: Country
      required:
      - code
      - name
      type: object
      properties:
        code:
          type: string
        name:
          type: string
      example:
        code: CA
        name: Canada
    Currentuserresponse:
      title: Currentuserresponse
      required:
      - uid
      - name
      - mail
      - eca
      - is_committer
      - friends
      - first_name
      - last_name
      - twitter_handle
      - org
      - job_title
      - website
      - country
      - bio
      - interests
      type: object
      properties:
        uid:
          type: string
        name:
          type: string
        mail:
          type: string
        eca:
          $ref: '#/components/schemas/Eca'
        is_committer:
          type: boolean
        friends:
          $ref: '#/components/schemas/Friends'
        first_name:
          type: string
        last_name:
          type: string
        twitter_handle:
          type: string
        org:
          type: string
        job_title:
          type: string
        website:
          type: string
        country:
          $ref: '#/components/schemas/Country'
        bio:
          type: string
        interests:
          type: array
          items:
            type: string
          description: ''
      example:
        uid: 9
        name: cguindon
        mail: chris.guindon@eclipse-foundation.org
        eca:
          signed: true
        is_committer: true
        friends:
          friend_id: 6104
        first_name: Christopher
        last_name: Guindon
        twitter_handle: chrisguindon
        org: Eclipse Foundation
        job_title: Lead Web Application Developper
        website: http://www.chrisguindon.com/
        country:
          code: CA
          name: Canada
        bio: Hello world! When I am not at a computer, which is rare, I spend my time playing the drums, watching hockey or at the top of a hill snowboarding. I am also very passionate about music and live concerts!
        interests:
        - Snowboarding
        - webdev
        - php
        - javascript
        - Drums
  headers:
    X-RateLimit-Reset:
      schema:
        type: string
      example: 3553
    X-RateLimit-Remaining:
      schema:
        type: string
      example: 964
    X-RateLimit-Limit:
      schema:
        type: string
      example: 1000
  securitySchemes:
    oauth2:
      description: 'Get access to data while protecting your account credentials.

        OAuth2 is also a safer and more secure way to give you access.

        '
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.php55.dev.docker/oauth2/authorize
          tokenUrl: https://accounts.php55.dev.docker/oauth2/token
          scopes:
            write: Grants write access
            read: Grants read access
